modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/auto-dropper/issues"
license="All rights reserved"

[[mods]]
modId="autodropper"
version="1.18-9.0.0"
displayName="Auto Dropper"
# updateJSONURL=""
displayURL="https://minecraft.curseforge.com/projects/auto-dropper"
# logoFile="logo.png"
# credits=""
authors="Ruuubi"
description='''Adds an automated version of Minecraft's Dropper'''

[[dependencies.autodropper]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.4,)"
    ordering="NONE"
	side="BOTH"