modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/auto-dropper/issues"
license="All rights reserved"

[[mods]]
modId="autodropper"
version="1.16.3-7.0.0"
displayName="Auto Dropper"
# updateJSONURL=""
displayURL="https://minecraft.curseforge.com/projects/auto-dropper"
# logoFile="logo.png"
# credits=""
authors="Ruuubi"
description='''Adds an automated version of Minecraft's Dropper'''

[[dependencies.autodropper]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.1,)"
    ordering="NONE"
	side="BOTH"