modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/auto-dropper/issues"

[[mods]]
modId="autodropper"
version="1.15.1-6.0.0"
displayName="Auto Dropper"
# updateJSONURL=""
displayURL="https://minecraft.curseforge.com/projects/auto-dropper"
# logoFile="logo.png"
# credits=""
authors="Ruuubi"
description='''Adds an automated version of Minecraft's Dropper'''

[[dependencies.autodropper]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.41,)"
    ordering="NONE"
	side="BOTH"